// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6BMC6UYPdVs8E-ntVsJp_xfSc3WTBoZY',
    appId: '1:994495544268:web:86e8100e675b1a7ae83b69',
    messagingSenderId: '994495544268',
    projectId: 'taskflow-ai-assistant',
    authDomain: 'taskflow-ai-assistant.firebaseapp.com',
    storageBucket: 'taskflow-ai-assistant.firebasestorage.app',
    measurementId: 'G-1RGG1FZ3W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZyHzoqvVXEYwm_AeN-l2joKqVbZAOfqI',
    appId: '1:994495544268:android:fffabacf9e199b62e83b69',
    messagingSenderId: '994495544268',
    projectId: 'taskflow-ai-assistant',
    storageBucket: 'taskflow-ai-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlvqcxJUixxbf4yRvwEKkr3QSy-z_RoDk',
    appId: '1:994495544268:ios:bd1b3e1936215e55e83b69',
    messagingSenderId: '994495544268',
    projectId: 'taskflow-ai-assistant',
    storageBucket: 'taskflow-ai-assistant.firebasestorage.app',
    iosClientId:
        '994495544268-7s7ljl658du883g2orspb8djor1rlqnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskflowAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlvqcxJUixxbf4yRvwEKkr3QSy-z_RoDk',
    appId: '1:994495544268:ios:bd1b3e1936215e55e83b69',
    messagingSenderId: '994495544268',
    projectId: 'taskflow-ai-assistant',
    storageBucket: 'taskflow-ai-assistant.firebasestorage.app',
    iosClientId:
        '994495544268-7s7ljl658du883g2orspb8djor1rlqnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskflowAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6BMC6UYPdVs8E-ntVsJp_xfSc3WTBoZY',
    appId: '1:994495544268:web:ba5ec7558c0f5292e83b69',
    messagingSenderId: '994495544268',
    projectId: 'taskflow-ai-assistant',
    authDomain: 'taskflow-ai-assistant.firebaseapp.com',
    storageBucket: 'taskflow-ai-assistant.firebasestorage.app',
    measurementId: 'G-YTPE8D44QM',
  );
}

// Platform  Firebase App Id
// web       1:994495544268:web:86e8100e675b1a7ae83b69
// android   1:994495544268:android:fffabacf9e199b62e83b69
// ios       1:994495544268:ios:bd1b3e1936215e55e83b69
// macos     1:994495544268:ios:bd1b3e1936215e55e83b69
// windows   1:994495544268:web:ba5ec7558c0f5292e83b69
